debug=true
server.port=8081
spring.name=api-gateway

spring.cloud.gateway.routes[0].id=posts-route
spring.cloud.gateway.routes[0].uri=https://jsonplaceholder.typicode.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/posts/**

management.endpoints.web.exposure.include=*